apiVersion: v1
kind: Pod
metadata:
  name: todoapp
spec:
  containers:
  - name: todoapp
    image: vhurna/todoapp:3.0.0
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /live
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
